spring:
  application:
    name: zuul-api-gateway-keycloak
#  profiles:
#    active: ssltest
---
spring:
  profiles: test
---
spring:
  profiles: cloud
---
spring:
  profiles: ssltest
server:
  ssl:
    enabled: true
    key-alias: ${spring.application.name}
    key-store: classpath:${spring.application.name}.p12
    key-store-type: PKCS12
    key-store-password: password
  port: 8445
security:
  require-ssl: true
  basic:
    enabled: false
eureka:
  client:
    enabled: false
https:
  enforcer:
    enabled: true
---